baseurl = "http://firoyang.org/"
title = "Firo Notes"
languageCode = "en-us"
disqusShortname = "firoyang"
MetaDataFormat = "toml"
pluralizelisttitles = false
pygmentsUseClasses = false
pygmentsStyle = "monokai"

[author]
    name = "Firo Yang"

[indexes]
    tag = "tags"
    topic = "topics"

[blackfriday]
    extensions = ["hardLineBreak"]
